-- Solicitudes de los formularios de la web.
-- El Worker (/api/contacto) inserta con la clave service_role, que se salta RLS.
-- El panel interno (integracionCRM-panel) lee y actualiza con la sesión de la
-- persona, y solo si su email está en panel_usuarios.
-- Se puede ejecutar varias veces sin romper nada.

create table if not exists public.contactos (
  id bigint generated by default as identity primary key,
  creado_en timestamptz not null default now(),
  tipo text,
  nombre text not null,
  email text not null,
  telefono text,
  empresa text,
  crm text,
  objetivo text,
  plataforma text,
  fecha text,
  hora text
);

-- Seguimiento comercial desde el panel
alter table public.contactos
  add column if not exists estado text not null default 'nuevo'
    check (estado in ('nuevo', 'contactado', 'cualificado', 'descartado')),
  add column if not exists puntuacion int not null default 50
    check (puntuacion between 0 and 100),
  add column if not exists responsable text,
  add column if not exists origen text not null default 'Web';

alter table public.contactos enable row level security;

-- Quién puede entrar al panel
create table if not exists public.panel_usuarios (
  email text primary key
);
alter table public.panel_usuarios enable row level security;

insert into public.panel_usuarios (email)
values ('info@integracioncrm.com'), ('herrerodelgadomario@gmail.com')
on conflict do nothing;

create or replace function public.es_usuario_panel()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.panel_usuarios
    where email = lower(auth.jwt() ->> 'email')
  );
$$;

drop policy if exists "panel lee contactos" on public.contactos;
create policy "panel lee contactos" on public.contactos
  for select to authenticated using (public.es_usuario_panel());

drop policy if exists "panel crea contactos" on public.contactos;
create policy "panel crea contactos" on public.contactos
  for insert to authenticated with check (public.es_usuario_panel());

drop policy if exists "panel actualiza contactos" on public.contactos;
create policy "panel actualiza contactos" on public.contactos
  for update to authenticated using (public.es_usuario_panel()) with check (public.es_usuario_panel());
