create table if not exists public.contactos (
  id bigint generated by default as identity primary key,
  creado_en timestamptz not null default now(),
  tipo text,
  nombre text not null,
  email text not null,
  telefono text,
  empresa text,
  crm text,
  objetivo text,
  plataforma text,
  fecha text,
  hora text
);

alter table public.contactos enable row level security;