-- Contador de visitas propio de integracioncrm.com (sin cookies ni identificadores).
-- Cada página vista guarda: ruta, dominio de procedencia, país, tipo de dispositivo
-- y si es el inicio de una visita (llega de fuera o directa). Nada más: ni IP, ni
-- navegador concreto, ni ningún identificador de la persona.
-- Se puede ejecutar varias veces sin romper nada.

create table if not exists public.visitas (
  id bigint generated by default as identity primary key,
  creado_en timestamptz not null default now(),
  pagina text not null,
  referente text,
  pais text,
  dispositivo text,
  nueva boolean not null default false
);
create index if not exists visitas_creado_en_idx on public.visitas (creado_en desc);

alter table public.visitas enable row level security;
drop policy if exists "panel lee visitas" on public.visitas;
create policy "panel lee visitas" on public.visitas
  for select to authenticated using (public.es_usuario_panel());

-- Entrada desde la web (clave publishable). Valida y limita abusos.
create or replace function public.registrar_visita(datos jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_pagina text := left(coalesce(datos ->> 'pagina', ''), 200);
begin
  if v_pagina !~ '^/' then
    return;
  end if;
  if (select count(*) from public.visitas where creado_en > now() - interval '1 hour') >= 3000 then
    return;
  end if;
  insert into public.visitas (pagina, referente, pais, dispositivo, nueva)
  values (
    v_pagina,
    nullif(left(trim(datos ->> 'referente'), 120), ''),
    nullif(upper(left(trim(datos ->> 'pais'), 2)), ''),
    nullif(left(trim(datos ->> 'dispositivo'), 20), ''),
    coalesce((datos ->> 'nueva')::boolean, false)
  );
end;
$$;
revoke all on function public.registrar_visita(jsonb) from public;
grant execute on function public.registrar_visita(jsonb) to anon, authenticated;

-- Resumen para el panel: todo agregado en la base de datos, días en hora de Madrid
create or replace function public.resumen_visitas(dias int default 30)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  n int := greatest(1, least(coalesce(dias, 30), 366));
  hoy date := (now() at time zone 'Europe/Madrid')::date;
  desde date := hoy - (n - 1);
  r jsonb;
begin
  if not public.es_usuario_panel() then
    raise exception 'Sin acceso';
  end if;

  with v as (
    select *, (creado_en at time zone 'Europe/Madrid')::date as dia
    from public.visitas
    where creado_en >= (desde::timestamp at time zone 'Europe/Madrid')
  )
  select jsonb_build_object(
    'desde', desde,
    'hasta', hoy,
    'vistas', (select count(*) from v),
    'visitas', (select count(*) filter (where nueva) from v),
    'ultima', (select max(creado_en) from public.visitas),
    'porDia', (
      select coalesce(jsonb_agg(jsonb_build_object('fecha', g.dia, 'vistas', coalesce(x.vistas, 0), 'visitas', coalesce(x.visitas, 0)) order by g.dia), '[]'::jsonb)
      from (select generate_series(desde, hoy, interval '1 day')::date as dia) g
      left join (select dia, count(*) as vistas, count(*) filter (where nueva) as visitas from v group by dia) x on x.dia = g.dia
    ),
    'paginas', (
      select coalesce(jsonb_agg(t), '[]'::jsonb) from (
        select pagina, count(*) as vistas, count(*) filter (where nueva) as visitas
        from v group by pagina order by count(*) desc limit 50
      ) t
    ),
    'origenes', (
      select coalesce(jsonb_agg(t), '[]'::jsonb) from (
        select coalesce(referente, '') as origen, count(*) as visitas
        from v where nueva group by 1 order by 2 desc limit 15
      ) t
    ),
    'dispositivos', (
      select coalesce(jsonb_agg(t), '[]'::jsonb) from (
        select coalesce(dispositivo, 'desconocido') as dispositivo, count(*) as vistas
        from v group by 1 order by 2 desc
      ) t
    ),
    'paises', (
      select coalesce(jsonb_agg(t), '[]'::jsonb) from (
        select coalesce(pais, '??') as pais, count(*) as vistas
        from v group by 1 order by 2 desc limit 10
      ) t
    )
  ) into r;
  return r;
end;
$$;
revoke all on function public.resumen_visitas(int) from public;
grant execute on function public.resumen_visitas(int) to authenticated;

notify pgrst, 'reload schema';
